services:
  qkd_ldpc:
    build: .
    image: qkd_ldpc_v:latest
    container_name: qkd_ldpc
    volumes:
      - ./sparse_matrices:/app/sparse_matrices
      - ./results:/app/results
      - ./configs:/app/configs
